<?PHP

/********* INICIALIZA LOS VALORES PRESENTADOS EN LA TABLA *********/



            // Create field variables based on database fields	
		
            $antfldRADICADO     ="";
            $antfldEXP          ="";
            $antfldNOMBRE       ="";
            $antfldDEPENDENCIA  ="";
            $antfldF_PEDIDO     ="";
            $antfldF_CANC       ="";			
            $antfldF_PRESTADO   ="";
            $antfldF_VENCIDO    ="";
            $antfldF_DEVUELTO   ="";
            $antfldREQUERIMIENTO="";
            $antfldNumPag       ="";
            $antfldESTADO       ="";
            $antfldID_ESTADO    ="";						
            $antfldLOGIN_PRES   ="";
            $antfldLOGIN_RX     ="";
            $antfldLOGIN_CANC   ="";
            $antfldLOGIN_ACTU   ="";
            $antfldPRESTAMO_ID  ="";
            $antfldDEPE_CODI    ="";
            $antfldARCH         ="";	
  	    $antaccion          ="";
 	    $antdifFecha        ="";
?>		 